MAX_AGENTS = 10
MAX_AGENT_NAME_LENGTH = 64
MAX_SYSTEM_PROMPT_LENGTH = 4096

MIN_TEMPERATURE = 0.0
MAX_TEMPERATURE = 2.0
DEFAULT_TEMPERATURE = 0.7

MIN_MAX_TOKENS = 100
MAX_MAX_TOKENS = 4096
DEFAULT_MAX_TOKENS = 1000

MAX_CONVERSATION_HISTORY = 100
MAX_PROMPT_VARIABLES = 20
MAX_VARIABLE_NAME_LENGTH = 32
MAX_VARIABLE_VALUE_LENGTH = 512

SUPPORTED_MODELS = [
    "llama-3.3-70b-versatile",
    "llama-3.3-70b-specdec",
    "llama-3.1-70b-versatile",
    "gemma2-9b-it",
]
DEFAULT_MODEL = "llama-3.3-70b-versatile"

SUCCESS_CODE = "success"
ERROR_CODE = "error"
NOT_FOUND_CODE = "not_found"
